CREATE TABLE IF NOT EXISTS `STATISTIC` (
  `ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `DOWNLOAD_WORD_TEMPLATE` INT NOT NULL DEFAULT 0,
  `DOWNLOAD_DFID_TEMPLATE` INT NOT NULL DEFAULT 0,
  `DOWNLOAD_XLSX_TEMPLATE` INT NOT NULL DEFAULT 0,
  `DOWNLOAD_PRM_TEMPLATE` INT NOT NULL DEFAULT 0,
  `DATE` TIMESTAMP NOT NULL
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

ALTER TABLE IND_INDICATOR ADD COLUMN TIMES_DOWNLOADED INT NOT NULL DEFAULT 0;