CREATE TABLE IF NOT EXISTS USERS
(
    USERNAME       VARCHAR(50) NOT NULL PRIMARY KEY,
    PASSWORD       VARCHAR(50) NOT NULL,
    ENABLED        BOOLEAN     NOT NULL,
    CREATED_BY     VARCHAR(50),
    CREATED_AT     TIMESTAMP,
    LAST_UPDATE_BY VARCHAR(50),
    UPDATED_AT     TIMESTAMP,
    UPDATED_BY     VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS `GROUPS`
(
    ID             BIGINT PRIMARY KEY,
    GROUP_NAME     VARCHAR(50) NOT NULL UNIQUE,
    CREATED_BY     VARCHAR(50),
    CREATED_AT     TIMESTAMP,
    LAST_UPDATE_BY VARCHAR(50),
    UPDATED_AT     TIMESTAMP,
    UPDATED_BY     VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS GROUP_AUTHORITIES
(
    GROUP_ID  BIGINT      NOT NULL,
    AUTHORITY VARCHAR(50) NOT NULL,
    CONSTRAINT FK_GROUP_AUTHORITIES_GROUP FOREIGN KEY (GROUP_ID) REFERENCES `GROUPS` (ID)
);

CREATE TABLE IF NOT EXISTS GROUP_MEMBERS
(
    ID             BIGINT AUTO_INCREMENT PRIMARY KEY,
    USERNAME       VARCHAR(50) NOT NULL,
    GROUP_ID       BIGINT      NOT NULL,
    CREATED_BY     VARCHAR(50),
    CREATED_AT     TIMESTAMP,
    LAST_UPDATE_BY VARCHAR(50),
    UPDATED_AT     TIMESTAMP,
    UPDATED_BY     VARCHAR(50),
    CONSTRAINT FK_GROUP_MEMBERS_USER FOREIGN KEY (USERNAME) REFERENCES USERS (USERNAME),
    CONSTRAINT FK_GROUP_MEMBERS_GROUP FOREIGN KEY (GROUP_ID) REFERENCES `GROUPS` (ID)
);

INSERT INTO `GROUPS` (ID, GROUP_NAME)
VALUES (1, 'ADMIN'),
       (2, 'USER'),
       (3, 'SEC_ADMIN');

INSERT INTO GROUP_AUTHORITIES
VALUES (1, 'CRUD_USER'),
       (2, 'READ_USER'),
       (2, 'READ_ADMIN'),
       (3, 'CRUD_ADMIN');

